config/routes.rb
Rails.application.routes.draw do
  get 'pages/info'

  root :to => redirect('/colorpalettes')
  get    '/colorpalettes'           => 'colorpalettes#index'

  get    '/colorpalettes/new'       => 'colorpalettes#new', as: 'new_colorpalette'
  get    '/colorpalettes/:id/edit'  => 'colorpalettes#edit', as: 'edit_colorpalette'
  get    '/colorpalettes/:id'       => 'colorpalettes#show', as: 'colorpalette'

  post   '/colorpalettes'           => 'colorpalettes#create'
  patch  '/colorpalettes/:id'       => 'colorpalettes#update'
  put    '/colorpalettes/:id'       => 'colorpalettes#update'

  delete '/colorpalettes/:id'       => 'colorpalettes#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/colorpalette.rb
class Colorpalette < ApplicationRecord
  mount_uploader :picture, PictureUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/colorpalettes_controller.rb
class ColorpalettesController < ApplicationController
  def index
    @colorpalettes = Colorpalette.all
    render 'index'
  end
  def show
    @colorpalette = Colorpalette.find(params[:id])
    render 'show'
  end
  def new
    @colorpalette = Colorpalette.new
    render 'new'
  end
  def edit
    @colorpalette = Colorpalette.find(params[:id])
    render 'edit'
  end
  def create
    @colorpalette = Colorpalette.new(colorpalette_params)
    if @colorpalette.save
      redirect_to @colorpalette, notice: 'Colorpalette was successfully created.'
    else
      render action: 'new'
    end
  end
  def update
    @colorpalette = Colorpalette.find(params[:id])
    if @colorpalette.update(colorpalette_params)
      redirect_to @colorpalette, notice: 'Colorpalette was successfully updated.'
    else
      render action: 'edit'
    end
  end
  def destroy
    @colorpalette = Colorpalette.find(params[:id])
    @colorpalette.destroy
    redirect_to colorpalettes_url, notice: 'Colorpalette was successfully destroyed.'
  end
  private
  # Only allow a trusted parameter "white list" through.
  def colorpalette_params
    params.require(:colorpalette).permit(:name, :description, :picture)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def info
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/colorpalettes/_form.html.erb
<%= form_with(model: colorpalette, local: true) do |form| %>
  <% if colorpalette.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(colorpalette.errors.count, "error") %> prohibited this colorpalette from being saved:</h2>

      <ul>
      <% colorpalette.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :colorpalette_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :colorpalette_description %>
  </div>

  <div class="field">
    <%= form.label :picture %>
    <%= form.file_field :picture, id: :colorpalette_picture %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/colorpalettes/edit.html.erb
<h1>Editing Colorpalette</h1>

<%= render 'form', colorpalette: @colorpalette %>

<%= link_to 'Show', @colorpalette %> |
<%= link_to 'Back', colorpalettes_path %>

app/views/colorpalettes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Colorpalettes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Picture</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @colorpalettes.each do |colorpalette| %>
      <tr>
        <td><%= colorpalette.name %></td>
        <td><%= colorpalette.description %></td>
        <td><%= image_tag(colorpalette.picture_url, :width => 200) if colorpalette.picture.present? %></td>
        <td><%= link_to 'Show', colorpalette %></td>
        <td><%= link_to 'Edit', edit_colorpalette_path(colorpalette) %></td>
        <td><%= link_to 'Destroy', colorpalette, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Colorpalette', new_colorpalette_path %>

app/views/colorpalettes/new.html.erb
<h1>New Colorpalette</h1>

<%= render 'form', colorpalette: @colorpalette %>

<%= link_to 'Back', colorpalettes_path %>

app/views/colorpalettes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @colorpalette.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @colorpalette.description %>
</p>

<p>
  <strong>Picture:</strong>
  <%= image_tag(@colorpalette.picture_url) if @colorpalette.picture.present? %>

</p>

<%= link_to 'Edit', edit_colorpalette_path(@colorpalette) %> |
<%= link_to 'Back', colorpalettes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Color Palette</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class='navbar navbar-default navbar-fixed-top' role='navigation'>
      <div class='container'>
        <div class='navbar-header'>
          <a class='navbar-brand' href='/'>The Color App</a>
        </div>
        <ul class='nav navbar-nav'>
          <li>
            <a href='/colorpalettes'>Collections</a>
          </li>
        </ul>
      </div>
    </nav>

    <div class='container'>
      <%= yield %>
    </div>

    <footer>
      <div class='container'>
        Rails Girls Stockholm 2017
      </div>
    </footer>

  </body>
</html>

app/views/pages/info.html.erb
<h1>Made by Magda</h1>
<p>This is the color palette tool made for choosing from nice colors which I have saved, so that you don't have to look them up every time!</p>